#! /bin/sh
#
# System-V init script for the lighttpd web server
# Modified by J.C. Woltz <jwoltz@gmail.com>
# 201201011219 Added check for log dir. Since /var/log can be on its own at times
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="lighttpd web server"
NAME=lighttpd
DAEMON=/usr/sbin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0
# Make the log dirrectory in case it is missing
test -d /var/log/lighttpd || mkdir /var/log/lighttpd

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
	/usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
	echo "."
	;;
  stop) echo -n "Stopping $DESC: $NAME"
	#start-stop-daemon -K -q -n $NAME
	/bin/kill `/bin/cat /var/run/lighttpd.pid`
	echo "."
	;;
  reload|force-reload) echo -n "Reloading $DESC configuration..."
	start-stop-daemon -K -q -n $NAME -s 1
	echo "done."
  ;;
  restart) echo "Restarting $DESC: $NAME"
	$0 stop
	sleep 1
	$0 start
	;;
  *) echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
